(function(){
'use strict';
var PIN_HASH='32ea6aa8091a36e8779df25bed19f857a402b1f3862c8c07212928f0f2ea886d';
var pinShell=document.getElementById('pin-shell'),app=document.getElementById('portal-app'),main=document.getElementById('portal-main');
function esc(s){return String(s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]});}
async function hash(v){var b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,'0');}).join('');}
function unlock(){sessionStorage.setItem('simworx-admin-review','1');pinShell.classList.add('hidden');app.classList.remove('hidden');render('dashboard');}
document.getElementById('pin-form').addEventListener('submit',async function(e){e.preventDefault();var ok=(await hash(document.getElementById('pin-input').value))===PIN_HASH;if(ok){unlock();}else{document.getElementById('pin-error').classList.remove('hidden');}});
document.getElementById('portal-signout').onclick=function(){sessionStorage.removeItem('simworx-admin-review');location.reload();};
document.querySelectorAll('#portal-nav button[data-view]').forEach(function(b){b.onclick=function(){document.querySelectorAll('#portal-nav button').forEach(function(x){x.classList.remove('active');});b.classList.add('active');render(b.dataset.view);};});
document.getElementById('mobile-nav-toggle').onclick=function(){document.querySelector('.portal-sidebar').classList.toggle('open');};
function tick(){var c=document.getElementById('portal-clock');if(c)c.textContent=new Date().toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});}tick();setInterval(tick,1000);
function shell(title,body){main.innerHTML='<div class="review-note"><strong>Review build:</strong> this /admin area is isolated from the public Simworx navigation and marked noindex/nofollow.</div><div class="page-head"><div><div class="eyebrow">SIMWORX SUPPORT</div><h1>'+esc(title)+'</h1></div></div>'+body;}
function requestsTable(){return '<table class="preview-table"><thead><tr><th>Reference</th><th>Customer</th><th>Subject</th><th>Priority</th><th>Status</th></tr></thead><tbody><tr><td>SWX-1042</td><td>JetPro Training</td><td>DA62 avionics display</td><td>P2</td><td>Diagnosing</td></tr><tr><td>SWX-1041</td><td>JetPro Training</td><td>Pedal firmware update</td><td>P3</td><td>Awaiting approval</td></tr><tr><td>SWX-1038</td><td>JetPro Training</td><td>Remote session</td><td>P3</td><td>Resolved</td></tr></tbody></table>';}
function render(v){
 if(v==='dashboard')return shell('Dashboard','<div class="preview-grid"><div class="preview-card">OPEN REQUESTS<strong>4</strong><span>Across active customer contracts</span></div><div class="preview-card">AWAITING APPROVAL<strong>1</strong><span>Additional engineering time requested</span></div><div class="preview-card">SUPPORT USED<strong>6h 25m</strong><span>11h 35m remaining this period</span></div></div><div class="card" style="margin-top:16px"><div class="card-body"><h3>Recent support requests</h3>'+requestsTable()+'</div></div>');
 if(v==='requests'||v==='my-requests'||v==='history')return shell(v==='history'?'Support history':v==='my-requests'?'My Open Requests':'Support Requests','<div class="card"><div class="card-body">'+requestsTable()+'<div style="margin-top:20px"><h3>Request SWX-1042 — DA62 avionics display</h3><div class="preview-chat"><div class="bubble"><strong>Customer</strong><br>The right PFD is intermittently freezing after start-up. I have attached a short video.</div><div class="bubble staff"><strong>Simworx Support</strong><br>Thanks. We can see the display service is dropping its connection. Please leave the simulator powered on and we will dial in remotely.</div><div class="bubble"><strong>Customer</strong><br>Simulator is online now. You can connect.</div></div></div></div></div>');
 if(v==='new-request')return shell('Log a Support Request','<div class="card"><div class="card-body"><div class="form-grid"><label>Customer<select><option>JetPro Training</option></select></label><label>Simulator<select><option>Diamond DA62 — JP-DA62-01</option></select></label><label>Priority<select><option>P2 — High</option></select></label><label>Category<select><option>Avionics / Displays</option></select></label></div><label>Subject<input value="DA62 avionics display issue"></label><label>Describe the problem<textarea rows="5">Please describe what happened, when it began, and any troubleshooting already attempted.</textarea></label><div style="margin-top:14px"><button class="sp-btn primary">CREATE SUPPORT REQUEST</button></div></div></div>');
 if(v==='usage')return shell('Usage & Upgrades','<div class="preview-grid"><div class="preview-card">MONTHLY ALLOWANCE<strong>18h</strong></div><div class="preview-card">USED<strong>6h 25m</strong></div><div class="preview-card">REMAINING<strong>11h 35m</strong></div></div><div class="card" style="margin-top:16px"><div class="card-body"><h3>Rates</h3><p>First-line engineering: €95/hour &nbsp; • &nbsp; Second-line engineering: €145/hour</p><div class="notice" style="margin-top:12px"><strong>Approval required: 1h additional second-line time</strong><br>Estimated €145.00 · 1.5× allowance usage</div></div></div>');
 if(v==='company')return shell('Company Information','<div class="card"><div class="card-body"><h3>JetPro Training</h3><p>Primary technical contact: Operations Team<br>Canada<br>DA62 simulator programme</p></div></div>');
 if(v==='contract')return shell('Support Contract','<div class="card"><div class="card-body"><h3>Premium Simulator Support</h3><p>Status: <strong>Active</strong><br>Monthly allowance: 18 hours<br>Support hours: Monday–Friday, 08:00–18:00 CET<br>Overage: approval required</p></div></div>');
 if(v==='downloads')return shell('Downloads','<div class="preview-grid"><div class="preview-card">REMOTE SUPPORT TOOL<strong style="font-size:16px">Download</strong></div><div class="preview-card">START-UP CHECKLIST<strong style="font-size:16px">PDF</strong></div><div class="preview-card">DA62 USER GUIDE<strong style="font-size:16px">PDF</strong></div></div>');
 if(v==='contact')return shell('Contact Us','<div class="card"><div class="card-body"><h3>Simworx Support</h3><p>Email: sales@sim-worx.com<br>Telephone: +34 868 480 623</p></div></div>');
 if(v==='admin')return shell('Administration','<div class="preview-grid"><div class="preview-card">CUSTOMERS<strong>1</strong><span>Manage companies and contacts</span></div><div class="preview-card">CONTRACTS<strong>1</strong><span>Rates, allowances and renewals</span></div><div class="preview-card">ENGINEERS<strong>0</strong><span>Assign support staff</span></div></div><div class="card" style="margin-top:16px"><div class="card-body"><h3>Customer administration</h3>'+requestsTable()+'</div></div>');
}
if(sessionStorage.getItem('simworx-admin-review')==='1')unlock();
})();